#sudo: false

language: cpp

notifications:
  email: true

os: linux
dist: trusty

env:
  global:
    - TMPDIR=/tmp

before_install:
  - pip install --user cpp-coveralls

matrix:
  include:
    - env: COMPILER=g++-8 BUILD_TYPE=Coverage
      addons: *gcc8

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "hfsm2_test.profdata" || echo "Codecov did not collect coverage reports."
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
