#sudo: false

language: cpp

notifications:
  email: true

os: linux
dist: trusty

env:
  global:
    - TMPDIR=/tmp

before_install:
  - pip install --user cpp-coveralls

matrix:
  include:

    # GCC 8
    - env: CC=gcc-8 CXX=g++-8 BUILD_TYPE=Coverage
      addons: &gcc8
        apt:
          packages: g++-8 lcov
          sources: ubuntu-toolchain-r-test

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake -DCMAKE_C_COMPILER=$CC X-DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make

after_success:
  - if [ "$BUILD_TYPE" = "Coverage" ]; then bash <(curl -s https://codecov.io/bash) -f "${TRAVIS_BUILD_DIR}/build/hfsm2_test.profdata" || echo "Codecov did not collect coverage reports" && coveralls --exclude lib --exclude tests --gcov-options '\-lp'; fi
